# NicheMapR + microclima

## How to use NicheMapR + microclima

Everything takes place in Rstudio

1. Install RNCEP, elevatr, NicheMapR, and microclima packages.

```
install.packages(c("RNCEP", "elevatr"))
install_github('mrke/NicheMapR', 'ilyamaclean/microclima')
```

2. Save the coordinates of the location of interest in an array. `lonlat <- c(lon, lat) # (longitude, latitude)`

3. Save the start and end date for which you want to obtain data for.
```
dstart <- paste0("01/0", month, "/2017") # start date
dfinish <- paste0("31/0", month, "/2017") # end date
```

3. Save 10 different depths below ground and save it as a variable. The values have to start from 0 and must have exactly 10 values regardless of what variables you are looking to obtain. `DEP <- c(0, 3, 5, 10, 15, 20, 30, 50, 100, 200)`

4. Run `micro_ncep()` with the above variables. Variables are stored under different category depending on what you are looking for. `?micro_ncep` will give you a list of what each category includes and how each variable is named. 

## Code example

***Getting hourly air temperatures in Nunn, CO (-104.73°, 40.87°) for January 1-31 in 2017*** 

```
install_github('mrke/NicheMapR')
install_github('ilyamaclean/microclima')

library(RNCEP)
library(elevatr)
library(NicheMapR)
library(microclima)


lonlat <- c(-104.73, 40.87) # (longitude, latitude)
dstart <- paste0("01/01/2017") # start date
dfinish <- paste0("31/01/2017") # end date

DEP <- c(0, 3, 5, 10, 15, 20, 30, 50, 100, 200) # need 10 depths regardless of what variables you are looking to obtain
micro <- micro_ncep(loc = lonlat, dstart = dstart, dfinish = dfinish, DEP = DEP,
                    runmoist = 0, runshade = 0)

vals <- micro$metout[, "TAREF"] # TAREF is the air temperature at reference height (2 m), which is stored under "metout".


days <- c()
for (i in 1:31) {
  days <- c(days, paste0("2017-01-", i))
}

offset <- 7 # Data are stored as UCT. So we need adjustment to be aligned to the local time.


df <- data.frame("Date" = rep(days, each = 24)[1 : (24 * 31 - offset)],
                 "Hour" = rep(0 : 23, 31)[1 : (24 * 31 - offset)],
                 "Data" = vals[(offset + 1) : (24 * 31)])


df$Date <- format(as.POSIXct(paste0(df$Date, " ", df$Hour, ":00")), format = "%Y-%m-%d %H:%M")

```
